### ISSUE TITLE
Node-Red on IOTstack can not open SQLite database 

### ISSUE THREAD

**Issue by lucibuz** [Paraphraser/IOTstackBackup#1]
Hello Phill,
First of all, sorry that I'm addressing this issue on this topic, but I couldn't find another way to address this to you.
I have a VM running Ubuntu server 20.10 and IOTstack, and all works well so far.
I managed to install SQLite using compose-override.yml.

services:
    sqlite3:
        container_name: sqlite3
        image: nouchka/sqlite3:latest
        stdin_open: true
        tty: true
        volumes:
            - "./volumes/sqlite3:/root/db/"
        restart: "unless-stopped"

SQLite database/tables works well (I use Portainer console to create db/tables), the issue I have is using SQLite with Node-red.

Node-Red can not access the database and I'm getting the following error:
Node-Red failed to open /home/iot/IOTstack/volumes/sqlite3/nodered.db

Can you help me on how to fix this issue?
Thanks in advance for your time

**Comment by Paraphraser** [comment]
Answered over on SensorsIot/IOTstack. By the way, I'm `@paraphraser` on the SensorsIot Discord channel so you can always reach me that way too.
